name: Go - Users Service
on:
  push:
    branches: [ "main" ]
    paths:
      - 'Backend/users/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Backend/users/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Build
      shell: bash
      run: |
        cd Backend/users
        go build -v
    - name: Test
      shell: bash
      run: |
        cd Backend/users
        go test -v ./...
