name: Go CI

on:
  push:
    branches:
      - main
    paths:
      - 'Backend/users/**'
  pull_request:
    branches:
      - main
    paths:
      - 'Backend/users/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.5'

    - name: Verify Go Modules
      run: |
        cd Backend/users
        ls -la  # Debugging to check if go.mod and go.sum exist
      shell: bash

    - name: Ensure Dependencies are Installed
      run: |
        cd Backend/users
        go mod tidy
        go mod download
      shell: bash

    - name: Build Users Service
      run: |
        cd Backend/users
        go build -v .
      shell: bash

    - name: Run Tests
      run: |
        cd Backend/users
        go test -v ./...
      shell: bash
