name: Go Users Service CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Backend/users  # Specify the users service directory

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Download Go dependencies
      run: go mod tidy

    - name: Build Users Service
      run: go build -v ./...

    - name: Run Tests
      run: go test -v ./...
