name: Debug Go Module Structure
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Explore Repository Structure
      run: |
        echo "Current directory: $(pwd)"
        echo "Repository contents:"
        ls -la
        echo "Backend directory contents:"
        ls -la Backend
        echo "Users directory contents:"
        ls -la Backend/users
        echo "Go Env:"
        go env
        echo "Go Mod file content:"
        cat Backend/users/go.mod
    - name: Try Different Build Approaches
      run: |
        echo "Approach 1: Building from root with full path"
        go build -v ./Backend/users/...
        
        echo "Approach 2: Change directory and build"
        cd Backend/users && go build -v
        
        echo "Approach 3: Change directory and build all packages"
        cd Backend/users && go build -v .
