name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Verify Go Modules
      working-directory: Backend/users
      run: |
        if [ ! -f go.mod ]; then
          echo "Error: go.mod file is missing. Ensure it is committed to the repository."
          exit 1
        fi
        go mod tidy
        ls -la

    - name: Build Users Service
      working-directory: Backend/users
      run: go build -v .

    - name: Run Tests
      working-directory: Backend/users
      run: go test -v .
