name: Go - Users Service
on:
  push:
    branches: [ "main" ]
    paths:
      - 'Backend/users/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Backend/users/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Debug Environment
      run: |
        pwd
        ls -la
        ls -la Backend || echo "Backend directory not found"
        ls -la Backend/users || echo "Users directory not found"
        cat Backend/users/go.mod || echo "go.mod not found"
    - name: Install Dependencies
      run: |
        cd Backend/users
        go mod download
    - name: Build
      run: |
        cd Backend/users
        go build -v
    - name: Test
      run: |
        cd Backend/users
        go test -v ./...
