name: Node.js CI
on:
  push:
    branches: [ "main" ]
    paths:
      - 'FE-UniBazaar/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'FE-UniBazaar/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v4
    
    - uses: pnpm/action-setup@v2
      with:
        version: 8.15.5  # ✅ Latest stable pnpm version

    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'
        cache-dependency-path: FE-UniBazaar/pnpm-lock.yaml  # ✅ Ensure correct path

    - run: pnpm install --no-frozen-lockfile  # ✅ Allows missing lock file
      working-directory: FE-UniBazaar

    - run: pnpm test
      working-directory: FE-UniBazaar
